from dataclasses import dataclass


@dataclass
class Help:
    mask:str = 'Mask existing data'
    extract:str = 'Extract data from ServiceNow'
    proccess:str = 'Process extracted data'
    stop_limit:str = ''
    file_limit:str = ''
    interval:str = ''
    batch_size:str = ''
    thread_id:str = ''
    extension:str = ''
    parallel:str = 'Specification of the number or extract rest API requests that will be invoked in parallel. The provided interval value is split based on this specification for achieving the concurrency.'
    username:str = 'ServiceNow acout username'
    password:str = 'ServiceNow acout password'
    start_date:str = 'Extraction start date in format YYYY-mm-dd'
    end_date:str = 'Extraction end date in format YYYY-mm-dd'
    url:str = 'Specification of ServiceNow table and filter in RestAPI terminology'
    id_list_path:str = 'Path to filtering file in csv format'
    id_field_name:str = 'Name of field in the filtering file'
    data_id_name:str = 'Name of field in the source data'
    export_and_mask:str = 'Perform masking during extraction'
    out_props_csv_path:str = 'Path to output csv containig extracted field set'
    out_prop_name:str = 'Name of the extracted propery'
    mapping_path:str = 'Path to csv file containg masking methods for columns'
    custom_token_dir:str = ''
    important_token_file:str = ''
    compress:str = 'Use this flag for applying compression on the files in outpu_dir (during their creation)'
    input_sources:str = 'coma separated filenames or directories containing json'
    input_dir:str = 'Directory that contains files for masking. The files should not be compressed.'
    output_dir:str = 'Directory that contains files that were created as part of --maks of --extract operation'
    version:str = 'Prints current version'
    config:str = ''
