from src.extractor_resource import Extractor
from logging import FileHandler

patched = False

UNITEST_OUTPUT_FILE_PREFIX = 'extracting_output/__unitest_output'
UNITEST_OUTPUT_FILE = f'{UNITEST_OUTPUT_FILE_PREFIX}.json'
UNITEST_OUTPUT_FILE_CSV = f'{UNITEST_OUTPUT_FILE_PREFIX}.csv'

def patch_for_tests():
    global patched
    if patched:
        return
    FileHandler._open = lambda a: None 
    # monkeypatch  to prevent files creation
    FileHandler._open = lambda a: None 
    FileHandler.emit = lambda a, b: None
    # monkeypatch Extractor for tests
    Extractor.get_output_filename = lambda self, params: UNITEST_OUTPUT_FILE_PREFIX if self.thread_id == 0 else f'{UNITEST_OUTPUT_FILE_PREFIX}_{self.thread_id}'


SNOW_RESPONSE_WITH_CUSTOM_ID = """
{
    "result": [
        {
            "attested_date": "",
            "skip_sync": "false",
            "operational_status": "1",
            "most_frequent_user": "",
            "sys_updated_on": "2021-10-04 15:17:58",
            "attestation_score": "",
            "discovery_source": "",
            "first_discovered": "",
            "sys_updated_by": "aes.creator",
            "due_in": "",
            "sys_created_on": "2021-10-04 15:17:58",
            "sys_domain": {
                "link": "https://dev71074.service-now.com/api/now/table/sys_user_group/global",
                "value": "global"
            },
            "install_date": "",
            "gl_account": "",
            "invoice_number": "",
            "sys_created_by": "aes.creator",
            "warranty_expiration": "",
            "asset_tag": "",
            "hardware_substatus": "",
            "fqdn": "",
            "change_control": "",
            "internet_facing": "true",
            "owned_by": "",
            "checked_out": "",
            "sys_domain_path": "/",
            "business_unit": "",
            "delivery_date": "",
            "maintenance_schedule": "",
            "hardware_status": "installed",
            "install_status": "1",
            "cost_center": "",
            "attested_by": "",
            "supported_by": "",
            "dns_domain": "",
            "name": "",
            "assigned": "",
            "life_cycle_stage": "",
            "purchase_date": "",
            "subcategory": "",
            "default_gateway": "",
            "short_description": "",
            "assignment_group": "",
            "managed_by": "",
            "managed_by_group": "",
            "can_print": "false",
            "last_discovered": "",
            "sys_class_name": "x_707785_ilyakapp_ilyak_test_table",
            "custom_sys_id": "123",
            "po_number": "",
            "checked_in": "",
            "sys_class_path": "/!!/!2/!8",
            "life_cycle_stage_status": "",
            "mac_address": "",
            "justification": "",
            "model_number": "",
            "department": "",
            "assigned_to": "",
            "start_date": "",
            "comments": "",
            "cost": "",
            "sys_mod_count": "0",
            "monitor": "false",
            "serial_number": "",
            "ip_address": "",
            "model_id": "",
            "sys_tags": "",
            "cost_cc": "USD",
            "order_date": "",
            "schedule": "",
            "support_group": "",
            "environment": "",
            "due": "",
            "attested": "false",
            "correlation_id": "",
            "unverified": "false",
            "attributes": "",
            "location": "",
            "asset": "",
            "category": "",
            "fault_count": "0",
            "lease_id": ""
        },
        {
            "attested_date": "",
            "skip_sync": "false",
            "operational_status": "1",
            "most_frequent_user": "",
            "sys_updated_on": "2021-10-04 15:17:58",
            "attestation_score": "",
            "discovery_source": "",
            "first_discovered": "",
            "sys_updated_by": "aes.creator",
            "due_in": "",
            "sys_created_on": "2021-10-04 15:17:58",
            "sys_domain": {
                "link": "https://dev71074.service-now.com/api/now/table/sys_user_group/global",
                "value": "global"
            },
            "install_date": "",
            "gl_account": "",
            "invoice_number": "",
            "sys_created_by": "aes.creator",
            "warranty_expiration": "",
            "asset_tag": "",
            "hardware_substatus": "",
            "fqdn": "",
            "change_control": "",
            "internet_facing": "true",
            "owned_by": "",
            "checked_out": "",
            "sys_domain_path": "/",
            "business_unit": "",
            "delivery_date": "",
            "maintenance_schedule": "",
            "hardware_status": "installed",
            "install_status": "1",
            "cost_center": "",
            "attested_by": "",
            "supported_by": "",
            "dns_domain": "",
            "name": "",
            "assigned": "",
            "life_cycle_stage": "",
            "purchase_date": "",
            "subcategory": "",
            "default_gateway": "",
            "short_description": "",
            "assignment_group": "",
            "managed_by": "",
            "managed_by_group": "",
            "can_print": "false",
            "last_discovered": "",
            "sys_class_name": "x_707785_ilyakapp_ilyak_test_table",
            "custom_sys_id": "456",
            "po_number": "",
            "checked_in": "",
            "sys_class_path": "/!!/!2/!8",
            "life_cycle_stage_status": "",
            "mac_address": "",
            "justification": "",
            "model_number": "",
            "department": "",
            "assigned_to": "",
            "start_date": "",
            "comments": "",
            "cost": "",
            "sys_mod_count": "0",
            "monitor": "false",
            "serial_number": "",
            "ip_address": "",
            "model_id": "",
            "sys_tags": "",
            "cost_cc": "USD",
            "order_date": "",
            "schedule": "",
            "support_group": "",
            "environment": "",
            "due": "",
            "attested": "false",
            "correlation_id": "",
            "unverified": "false",
            "attributes": "",
            "location": "",
            "asset": "",
            "category": "",
            "fault_count": "0",
            "lease_id": ""
        },
        {
            "attested_date": "",
            "skip_sync": "false",
            "operational_status": "1",
            "most_frequent_user": "",
            "sys_updated_on": "2021-10-04 15:17:58",
            "attestation_score": "",
            "discovery_source": "",
            "first_discovered": "",
            "sys_updated_by": "aes.creator",
            "due_in": "",
            "sys_created_on": "2021-10-04 15:17:58",
            "sys_domain": {
                "link": "https://dev71074.service-now.com/api/now/table/sys_user_group/global",
                "value": "global"
            },
            "install_date": "",
            "gl_account": "",
            "invoice_number": "",
            "sys_created_by": "aes.creator",
            "warranty_expiration": "",
            "asset_tag": "",
            "hardware_substatus": "",
            "fqdn": "",
            "change_control": "",
            "internet_facing": "true",
            "owned_by": "",
            "checked_out": "",
            "sys_domain_path": "/",
            "business_unit": "",
            "delivery_date": "",
            "maintenance_schedule": "",
            "hardware_status": "installed",
            "install_status": "1",
            "cost_center": "",
            "attested_by": "",
            "supported_by": "",
            "dns_domain": "",
            "name": "",
            "assigned": "",
            "life_cycle_stage": "",
            "purchase_date": "",
            "subcategory": "",
            "default_gateway": "",
            "short_description": "",
            "assignment_group": "",
            "managed_by": "",
            "managed_by_group": "",
            "can_print": "false",
            "last_discovered": "",
            "sys_class_name": "x_707785_ilyakapp_ilyak_test_table",
            "custom_sys_id": "669009b4874330105fd965f73cbb3533",
            "po_number": "",
            "checked_in": "",
            "sys_class_path": "/!!/!2/!8",
            "life_cycle_stage_status": "",
            "mac_address": "",
            "justification": "",
            "model_number": "",
            "department": "",
            "assigned_to": "",
            "start_date": "",
            "comments": "",
            "cost": "",
            "sys_mod_count": "0",
            "monitor": "false",
            "serial_number": "",
            "ip_address": "",
            "model_id": "",
            "sys_tags": "",
            "cost_cc": "USD",
            "order_date": "",
            "schedule": "",
            "support_group": "",
            "environment": "",
            "due": "",
            "attested": "false",
            "correlation_id": "",
            "unverified": "false",
            "attributes": "",
            "location": "",
            "asset": "",
            "category": "",
            "fault_count": "0",
            "lease_id": ""
        }
    ]
}
"""

SNOW_RESPONSE1 = """
{
    "result": [
        {
            "attested_date": "",
            "skip_sync": "false",
            "operational_status": "1",
            "most_frequent_user": "",
            "sys_updated_on": "2021-10-04 15:17:58",
            "attestation_score": "",
            "discovery_source": "",
            "first_discovered": "",
            "sys_updated_by": "aes.creator",
            "due_in": "",
            "sys_created_on": "2021-10-04 15:17:58",
            "sys_domain": {
                "link": "https://dev71074.service-now.com/api/now/table/sys_user_group/global",
                "value": "global"
            },
            "install_date": "",
            "gl_account": "",
            "invoice_number": "",
            "sys_created_by": "aes.creator",
            "warranty_expiration": "",
            "asset_tag": "",
            "hardware_substatus": "",
            "fqdn": "",
            "change_control": "",
            "internet_facing": "true",
            "owned_by": "",
            "checked_out": "",
            "sys_domain_path": "/",
            "business_unit": "",
            "delivery_date": "",
            "maintenance_schedule": "",
            "hardware_status": "installed",
            "install_status": "1",
            "cost_center": "",
            "attested_by": "",
            "supported_by": "",
            "dns_domain": "",
            "name": "",
            "assigned": "",
            "life_cycle_stage": "",
            "purchase_date": "",
            "subcategory": "",
            "default_gateway": "",
            "short_description": "",
            "assignment_group": "",
            "managed_by": "",
            "managed_by_group": "",
            "can_print": "false",
            "last_discovered": "",
            "sys_class_name": "x_707785_ilyakapp_ilyak_test_table",
            "sys_id": "123",
            "po_number": "",
            "checked_in": "",
            "sys_class_path": "/!!/!2/!8",
            "life_cycle_stage_status": "",
            "mac_address": "",
            "justification": "",
            "model_number": "",
            "department": "",
            "assigned_to": "",
            "start_date": "",
            "comments": "",
            "cost": "",
            "sys_mod_count": "0",
            "monitor": "false",
            "serial_number": "",
            "ip_address": "",
            "model_id": "",
            "sys_tags": "",
            "cost_cc": "USD",
            "order_date": "",
            "schedule": "",
            "support_group": "",
            "environment": "",
            "due": "",
            "attested": "false",
            "correlation_id": "",
            "unverified": "false",
            "attributes": "",
            "location": "",
            "asset": "",
            "category": "",
            "fault_count": "0",
            "lease_id": ""
        },
        {
            "attested_date": "",
            "skip_sync": "false",
            "operational_status": "1",
            "most_frequent_user": "",
            "sys_updated_on": "2021-10-04 15:17:58",
            "attestation_score": "",
            "discovery_source": "",
            "first_discovered": "",
            "sys_updated_by": "aes.creator",
            "due_in": "",
            "sys_created_on": "2021-10-04 15:17:58",
            "sys_domain": {
                "link": "https://dev71074.service-now.com/api/now/table/sys_user_group/global",
                "value": "global"
            },
            "install_date": "",
            "gl_account": "",
            "invoice_number": "",
            "sys_created_by": "aes.creator",
            "warranty_expiration": "",
            "asset_tag": "",
            "hardware_substatus": "",
            "fqdn": "",
            "change_control": "",
            "internet_facing": "true",
            "owned_by": "",
            "checked_out": "",
            "sys_domain_path": "/",
            "business_unit": "",
            "delivery_date": "",
            "maintenance_schedule": "",
            "hardware_status": "installed",
            "install_status": "1",
            "cost_center": "",
            "attested_by": "",
            "supported_by": "",
            "dns_domain": "",
            "name": "",
            "assigned": "",
            "life_cycle_stage": "",
            "purchase_date": "",
            "subcategory": "",
            "default_gateway": "",
            "short_description": "",
            "assignment_group": "",
            "managed_by": "",
            "managed_by_group": "",
            "can_print": "false",
            "last_discovered": "",
            "sys_class_name": "x_707785_ilyakapp_ilyak_test_table",
            "sys_id": "456",
            "po_number": "",
            "checked_in": "",
            "sys_class_path": "/!!/!2/!8",
            "life_cycle_stage_status": "",
            "mac_address": "",
            "justification": "",
            "model_number": "",
            "department": "",
            "assigned_to": "",
            "start_date": "",
            "comments": "",
            "cost": "",
            "sys_mod_count": "0",
            "monitor": "false",
            "serial_number": "",
            "ip_address": "",
            "model_id": "",
            "sys_tags": "",
            "cost_cc": "USD",
            "order_date": "",
            "schedule": "",
            "support_group": "",
            "environment": "",
            "due": "",
            "attested": "false",
            "correlation_id": "",
            "unverified": "false",
            "attributes": "",
            "location": "",
            "asset": "",
            "category": "",
            "fault_count": "0",
            "lease_id": ""
        },
        {
            "attested_date": "",
            "skip_sync": "false",
            "operational_status": "1",
            "most_frequent_user": "",
            "sys_updated_on": "2021-10-04 15:17:58",
            "attestation_score": "",
            "discovery_source": "",
            "first_discovered": "",
            "sys_updated_by": "aes.creator",
            "due_in": "",
            "sys_created_on": "2021-10-04 15:17:58",
            "sys_domain": {
                "link": "https://dev71074.service-now.com/api/now/table/sys_user_group/global",
                "value": "global"
            },
            "install_date": "",
            "gl_account": "",
            "invoice_number": "",
            "sys_created_by": "aes.creator",
            "warranty_expiration": "",
            "asset_tag": "",
            "hardware_substatus": "",
            "fqdn": "",
            "change_control": "",
            "internet_facing": "true",
            "owned_by": "",
            "checked_out": "",
            "sys_domain_path": "/",
            "business_unit": "",
            "delivery_date": "",
            "maintenance_schedule": "",
            "hardware_status": "installed",
            "install_status": "1",
            "cost_center": "",
            "attested_by": "",
            "supported_by": "",
            "dns_domain": "",
            "name": "",
            "assigned": "",
            "life_cycle_stage": "",
            "purchase_date": "",
            "subcategory": "",
            "default_gateway": "",
            "short_description": "",
            "assignment_group": "",
            "managed_by": "",
            "managed_by_group": "",
            "can_print": "false",
            "last_discovered": "",
            "sys_class_name": "x_707785_ilyakapp_ilyak_test_table",
            "sys_id": "669009b4874330105fd965f73cbb3533",
            "po_number": "",
            "checked_in": "",
            "sys_class_path": "/!!/!2/!8",
            "life_cycle_stage_status": "",
            "mac_address": "",
            "justification": "",
            "model_number": "",
            "department": "",
            "assigned_to": "",
            "start_date": "",
            "comments": "",
            "cost": "",
            "sys_mod_count": "0",
            "monitor": "false",
            "serial_number": "",
            "ip_address": "",
            "model_id": "",
            "sys_tags": "",
            "cost_cc": "USD",
            "order_date": "",
            "schedule": "",
            "support_group": "",
            "environment": "",
            "due": "",
            "attested": "false",
            "correlation_id": "",
            "unverified": "false",
            "attributes": "",
            "location": "",
            "asset": "",
            "category": "",
            "fault_count": "0",
            "lease_id": ""
        }
    ]
}
"""